on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: verse.flatpak
        manifest-path: io.github.TanmayPatil105.verse.json
        cache-key: flatpak-builder-${{ github.sha }}
